name: Aliyun OSS

on: [push,delete]

jobs:
  OSS:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip oss]')"
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Setting ğŸ”§
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: ${{ secrets.ENDPOINT }}
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
          
      - name: Deply To OSS ğŸš€
        run: |
          ip=$(curl -s https://api.ip.sb/ip)
          ossutil rm oss://xhemj/ossutil_output/ -r -f
          ossutil cp ./ oss://xhemj/ -r -f
          ossutil rm oss://xhemj/.git/ -r -f
          ossutil rm oss://xhemj/.github/ -r -f
          ossutil set-meta oss://xhemj/src/ Cache-Control:public,max-age=86400 --include "*.js" --include "*.css" --include "*.min.js" -r -f
          echo success[$ip]