name: Aliyun OSS

on: [push,delete]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Setting ğŸ”§
        uses: manyuanrong/setup-ossutil@v1.0
        with:
          endpoint: ${{ secrets.ENDPOINT }}
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
          
      - name: Deply To OSS ğŸš€
        run: |
          ossutil cp ./ oss://xhemj/ -rf
          ossutil rm oss://xhemj/.git/ -r
          ossutil rm oss://xhemj/.github/ -r
