name: Aliyun OSS

on: [push,delete]

jobs:
  OSS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Setting ğŸ”§
        uses: fangbinwei/aliyun-oss-website-action@v1
        with:
          endpoint: ${{ secrets.ENDPOINT }}
          bucket: xhemj
          accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.ACCESS_KEY_SECRET }}
          folder: ./
          htmlCacheControl: max-age=600
          otherCacheControl: max-age=259200
          imageCacheControl: max-age=864000
          cname: true
          
      - name: Deply To OSS ğŸš€
        run: |
          ip=$(curl -s https://api.ip.sb/ip)
          ossutil cp ./ oss://xhemj/ -r -f
          ossutil rm oss://xhemj/.git/ -r -f
          ossutil rm oss://xhemj/.github/ -r -f
          ossutil du oss://xhemj
          echo success[$ip]